import * as pdfjsLib from 'pdfjs-dist'
// @ts-ignore - Vite-specific asset URL import for the pdf.js worker
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url'

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker

// pdf.js prints an internal "Setting up fake worker" notice whenever it
// falls back to processing a PDF on the main thread instead of a
// background worker. This is a known, harmless pdf.js behavior, not an
// error and not something this app's own code produces, PDF scanning
// still works correctly either way. It is filtered here purely so it
// doesn't show up as an alarming-looking line in the browser console.
const originalWarn = console.warn
console.warn = (...args: unknown[]) => {
  if (typeof args[0] === 'string' && args[0].includes('Setting up fake worker')) return
  originalWarn(...args)
}

export async function extractPdfText(file: File): Promise<string> {
  const buffer = await file.arrayBuffer()
  const pdf = await pdfjsLib.getDocument({ data: buffer }).promise
  let text = ''
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i)
    const content = await page.getTextContent()

    // BUGFIX: this used to join every text item on the page with a single
    // space, with no regard for line breaks. pdf.js does not hand back
    // paragraph or row breaks on its own, a real multi-row project plan
    // would have collapsed into one giant unparsable line. This groups
    // items into lines by comparing the vertical (y) position of each
    // text run's transform matrix, the standard technique for
    // reconstructing line breaks from pdf.js text content.
    let lastY: number | null = null
    let line = ''
    for (const raw of content.items) {
      if (!('str' in raw)) continue
      const item = raw as { str: string; transform: number[] }
      const y = item.transform[5]
      if (lastY !== null && Math.abs(y - lastY) > 2) {
        // BUGFIX: found via real testing with a browser-scanned PDF, not a
        // hypothetical. Every text item got a space appended unconditionally,
        // but reportlab (and PDF generators generally) can hand pdf.js the
        // same visual text split into a different number of glyph runs
        // depending on where it sits on the page, so the same task name
        // could come out with a different number of internal spaces
        // depending on whether it was extracted as a task's own name or
        // referenced inside another row's dependency list. That silently
        // broke exact-match dependency lookups downstream: every
        // dependency reference failed to resolve, and every task quietly
        // became a start task with no predecessors. Collapsing whitespace
        // to single spaces here, not just trimming the line ends, removes
        // the entire class of mismatch at the source instead of only
        // patching the one place it happened to surface.
        text += line.replace(/\s+/g, ' ').trim() + '\n'
        line = ''
      }
      line += item.str + ' '
      lastY = y
    }
    text += line.replace(/\s+/g, ' ').trim() + '\n'
  }
  return text
}

export interface ParsedRow {
  rawLine: string
  name: string
  duration: number
  dependencyNames: string[]
}

// Heuristic, tolerant parser. It is intentionally not a strict format, since
// PDFs exported from different tools (Excel, Word, project software) all
// lay out text slightly differently once pdf.js flattens it to a text
// stream. It tries a few common shapes per line and keeps whatever matches.
// The UI always shows the result for human review before anything is
// applied, the parser's job is to get close, not to be perfectly correct.
export function parseTaskLines(rawText: string): ParsedRow[] {
  const lines = rawText
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean)

  const rows: ParsedRow[] = []

  // Shape A: delimiter separated "Name ; Duration ; Dep1, Dep2"
  const delimiterPattern = /^(.{2,80}?)\s*[;|\t]\s*(\d{1,3})\s*(?:[;|\t]\s*(.*))?$/

  // Shape B: "Name 5 Tage (Dep1, Dep2)" or "Name - 5 days - Dep1, Dep2"
  const inlinePattern =
    /^(.{2,80}?)\s*[-–—]?\s*(\d{1,3})\s*(?:tage|days|أيام)?\s*(?:[-–—(]\s*([^)]*)\)?)?$/i

  // BUGFIX: found via real testing, not a hypothetical. A PDF's own title
  // page text (subtitle lines like "As of 08.20.2026", generated by every
  // demo PDF this app ships with) has no semicolon, so it fell through to
  // the loose Shape B fallback above. That pattern only requires *some*
  // 1-3 digit number near the end of the line, no "days/Tage" keyword
  // required, so it happily read the last three digits of a date as a
  // task duration and treated the whole subtitle as a fake task with zero
  // dependencies. That single phantom task then corrupted the entire
  // critical path calculation (wrong task count, wrong total duration,
  // absurd total float) with no visible error, since it looked like a
  // normal, if oddly named, task. Lines that carry a full date (DD.MM.YYYY
  // or similar) or the "·" separator this app's own PDF template uses
  // between title-page fields are rejected before either pattern is even
  // tried, since a genuine task name practically never contains a full
  // calendar date.
  const looksLikeMetadata = (line: string) => /\d{1,2}[./]\d{1,2}[./]\d{2,4}/.test(line) || line.includes('·')

  for (const line of lines) {
    if (looksLikeMetadata(line)) continue

    let match = line.match(delimiterPattern)
    let name = '',
      duration = 0,
      depsRaw = ''

    if (match) {
      name = match[1].trim()
      duration = parseInt(match[2], 10)
      depsRaw = (match[3] ?? '').trim()
    } else {
      match = line.match(inlinePattern)
      if (match) {
        name = match[1].trim()
        duration = parseInt(match[2], 10)
        depsRaw = (match[3] ?? '').trim()
      }
    }

    if (!name || !duration || duration <= 0 || duration > 365) continue
    // Skip lines that are almost certainly headers or noise.
    if (/^(name|task|vorgang|bezeichnung|المهمة|duration|dauer)$/i.test(name)) continue

    const dependencyNames = depsRaw
      .split(/[,،]/)
      .map((d) => d.trim())
      .filter((d) => d && !/^(none|keine|start|لا شيء)$/i.test(d))

    rows.push({ rawLine: line, name, duration, dependencyNames })
  }

  return rows
}
